version: "3.8"

services:
  app:
    build:
      args:
        user: paulo
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: vctrcardoso/laravel-docker
    working_dir: /var/www/
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./:/var/www
    networks:
      - laravel-docker
   

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-docker

  db:
    image: mysql:8.0.35
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - laravel-docker

    
  redis:
    image: redis:latest
    networks:
        - laravel-docker



networks:
  laravel-docker:
    driver: bridge




